### PR TITLE
feat(casper): update txn history endpoint to get failed txs

### PR DESCRIPTION
**Pull request by lawRathod**
Changes: 
* Change txn history endpoint to get list of failed txns as well.

### CODE REVIEW

**Review by emmanuelm41 — COMMENTED** [review]
Shouldn't we add the tx status when parsing the txs?

**Comment by emmanuelm41** [comment]
@lawRathod I think everything else is perfect! :D

**Comment by lawRathod** [comment]
> Shouldn't we add the tx status when parsing the txs?

Do you mean the error message @emmanuelm41 ?

**Comment by emmanuelm41** [comment]
> > Shouldn't we add the tx status when parsing the txs?
> 
> Do you mean the error message @emmanuelm41 ?

I meant this 
https://github.com/Zondax/ledger-live/blob/f8a4021541d03a67f53b04b0d70b7f4e3cb60d6c/libs/ledgerjs/packages/types-live/src/operation.ts#L95

**Comment by lawRathod** [comment]
Not sure I follow. We are doing this here https://github.com/Zondax/ledger-live/pull/12/files#diff-a58867f5f19440c63813ef03f6e20c4a063e1b3a522041b383a38858b7aec961R53

**Review by emmanuelm41 — APPROVED** [review]

**Comment by emmanuelm41** [comment]
> Not sure I follow. We are doing this here https://github.com/Zondax/ledger-live/pull/12/files#diff-a58867f5f19440c63813ef03f6e20c4a063e1b3a522041b383a38858b7aec961R53

My bad hahaha everything ready!!!

**Comment by lawRathod** [comment]
We may need to revert this PR...

**Comment by emmanuelm41** [comment]
> We may need to revert this PR...

Yes, I saw the casper lab message. Let's revert it if necessary.

**Pull request merged**
